### ISSUE TITLE
Just looked at the project to understand what it does. Here are a few comments.

### ISSUE THREAD

**Issue by rusty-snake** [trytomakeyouprivate/Arkenfox-softening#2]
1. Suggestion to pin `#1` and/or enable Github Discussions
2. This creates a user.js with an syntax errors
  https://github.com/trytomakeyouprivate/Arkenfox-softening/blob/926cd50530d049ccdbca424b2bcbb03e4317e026/arkenfox-script.sh#L18
  https://github.com/trytomakeyouprivate/Arkenfox-softening/blob/926cd50530d049ccdbca424b2bcbb03e4317e026/arkenfox-script.sh#L51
3. For what are those extra `""`? Note this is a bash script and not a python script
   https://github.com/trytomakeyouprivate/Arkenfox-softening/blob/926cd50530d049ccdbca424b2bcbb03e4317e026/arkenfox-script.sh#L31
4. LibreWolf patch?
  https://github.com/trytomakeyouprivate/Arkenfox-softening/blob/926cd50530d049ccdbca424b2bcbb03e4317e026/arkenfox-script.sh#L32

**Comment by trytomakeyouprivate** [comment]
Hi, the script was a total mess and yes It didnt work. I will look at your first issue, the other ones should be solved.

I made lots of things choosable now and I think I found an okay way to do this. It was a learning project for me, I did all that basically the first time.

It is now fundamentally changed and made simpler.

1. only one script patcher and chooser script, all you do is change the paths there
2. the chooser script should include all changes that are discussable, so nothing weird happens
3. many fixes
4. changes should not break things anymore

Thanks for the fix, forgot it was "//" and not "#". I changed the method to avoid needing "//" as it breaks sed somehow, maybe the symbols can be deactivated.

**Comment by trytomakeyouprivate** [comment]
Yes the librewolf patch doesnt make sense, but I keep it there as Arkenfox doesnt have settings that are unneeded, so if they may add this config, it will directly be removed ;D

**Comment by rusty-snake** [comment]
https://github.com/trytomakeyouprivate/Arkenfox-softening/blob/f4594a93f0aa4054cc4e871dfa8f59bfc311d175/arkenfox-script.sh#L89-L116

1. The first printf prints the unit and it's path to stdout but does not create any file
2. The second printf creates a timer unit in a file named .service staring itself.


> It was a learning project for me, I did all that basically the first time.

There's still a lot to learn.

**Comment by trytomakeyouprivate** [comment]
Thanks, fixed it now! 

Anything else missing? Maybe bad coding habits? I think it works quite well now, but still if something changes maybe other things break too, for example all these fixed deletion lines.

**Comment by rusty-snake** [comment]
https://github.com/trytomakeyouprivate/Arkenfox-softening/blob/debf051df1915264e9964ccbecf01c862e8f82ac/arkenfox-script.sh#L30

This will add a syntax error in the user.js

**Comment by trytomakeyouprivate** [comment]
Hi, the code was a complete mess. Should be cleaned up now.
