### ISSUE TITLE
Duplicates in user-overrides.js

### ISSUE THREAD

**Issue by parallelqw** [trytomakeyouprivate/Arkenfox-softening#5]
Any specific reason for keeping duplicates in file?
![image](https://github.com/trytomakeyouprivate/Arkenfox-softening/assets/96251537/ba836487-cf84-467d-a513-51c4b9811387)

I removed it, but since I am not sure why you did that, I didn't open a PR.

**Comment by trytomakeyouprivate** [comment]
no that will be a mistake ;D feel free to open a PR !
